### ISSUE TITLE
Peers Module

### ISSUE THREAD

**Issue by asutula** [textileio/powergate#191]
There is no existing PG abstraction for data about node peers, so for now we'll create a new PG Peers module that exposes the data available from Lotus apis. This will drive some of the web UI in addition to being generally available for any client.

**Comment by asutula** [comment]
@jsign, do you think we should implement this with a PG module that defines some simple data models and methods, or should we just pass the Lotus API straight into a gRPC service and implement it there?

**Comment by jsign** [comment]
Sounds like a better long-term plan to build the Peer Module abstraction. Most prob because will make things easier in the future to define some general-level API that a Filecoin node should provide. (To support other impl than Lotus).

**Comment by asutula** [comment]
Cool sounds like a plan.
