### ISSUE TITLE
RFC: Health, Peers, Net modules

### ISSUE THREAD

**Issue by asutula** [textileio/powergate#242]
There are potentially a few new modules we'll want to implement. They should be generally useful and will also help support the Lotus web UI project. I want to get my thoughts about the design and implementation written down to collect feedback and come up with a final plan.

To start, the three modules I imagine existing are Health, Peers and Net:

- **Health** - Provide information about the node health. This could be derived from many sources of information.
- **Peers** - Information about node peers. This will likely be augmented with derived data such as ip-based peer location. For this reason, it may be useful to think of/model this like an _index_ similar to the existing Miners index.
- **Net** - Provides general information about and methods for interacting with the network

The first pass at these modules can easily be supported by the "Net" methods of the Lotus API:

```
NetConnectedness func(context.Context, peer.ID) (network.Connectedness, error)
NetPeers         func(context.Context) ([]peer.AddrInfo, error)
NetConnect       func(context.Context, peer.AddrInfo) error
NetAddrsListen   func(context.Context) (peer.AddrInfo, error)
NetDisconnect    func(context.Context, peer.ID) error
NetFindPeer      func(context.Context, peer.ID) (peer.AddrInfo, error)
```

To begin, the single input to the Health module will be `NetConnectedness`. It's good to have Health as a module because we will add other sources of information to compute "health".

`NetPeers` can be queried on some interval (chain update maybe?) and augmented with derived data to build the peers index.

The remaining methods can be used to build the Net module with simple methods for taking the node on and offline and fining peers.

That is my first thought on how to model this. I think it is simple but gives us some flexibility going forward to incorporate other data sources and/or adapt to other Filecoin implementations.

**Comment by jsign** [comment]
Some questions:
1) Does the _Health_ module reports health of *my* node running in the network, or is trying to answer the _health_ question about external nodes? 
I was thinking about the former, since the UI doc refers to _health_ as for the local node. But the _NetConectedness_ comment about external peers makes me doubt about the module intentions.

2) Is the idea that only the _Net_ interface concrete implementation will depend on the Lotus API? Both _Health_ or _Peers_ will only use the _Net_ module.

**Comment by asutula** [comment]
1. I didn't think at all about health of external nodes, just the local node. Any requirement for health of external nodes (which I'm not sure if there is any requirement, maybe in one list of peer nodes in a mockup?) could be a thing we figure out later I think.
2. I was imagining that they would all use the Lotus API and that the `Net` module doesn't needs to expose methods that are effectively covered by the `Peers` and `Health` modules.

Those were just initial thoughts, and I'm completely flexible to doing this however makes sense. In this case, it seems the modules are very simple and there aren't many strong factors that would make one solution clearly better than another.

**Comment by jsign** [comment]
> 1. I didn't think at all about health of external nodes, just the local node. Any requirement for health of external nodes (which I'm not sure if there is any requirement, maybe in one list of peer nodes in a mockup?) could be a thing we figure out later I think.

Yeah, that's was my sensation too. I think I was confused by: 
> To begin, the single input to the Health module will be NetConnectedness. 

I guess you were thinking about gathering a bunch of those outputs to conclude a health-related metric about the local node? Sounds good.
Another idea is also considering what is tracked in the Grafana dashboard: if the height is going up at an expected rate. If that thing stalls, then there's definitely a problem.

> 2. I was imagining that they would all use the Lotus API and that the `Net` module doesn't need to expose methods that are effectively covered by the `Peers` and `Health` modules.

Well, my question was more about thinking if the three modules would have to deal with supporting different Filecoin client APIs, or maybe only `Net`, and the other two depend on the `Net` abstraction. 

I agree that now there isn't much stuff going on on those modules, so whatever way seems good now. We can later rethink the design when other Fil APIs come into place, or modules grow in features.

**Comment by asutula** [comment]
Exactly -- eventually we can add more data to the _local_ node health calculation. I love the idea of using some of the Grafana data.

Oh right, so if the other two modules only depend on our own `Net` abstraction, then there is less to change to support a different Filecoin implementation. I can see how it looks either way when I go to implement this.

**Comment by asutula** [comment]
@jsign do you have any new thoughts about the way we implement modules? Just as far as directory structure, naming, etc.

**Comment by jsign** [comment]
For the moment, I'd consider each module as a root folder in the repo.

In the modules that depend on Lotus API, I'd make subdirectories with implementations and leave the root folder to interfaces and types.
e.g: the `net` module/folder. `net/interface.go` with interfaces and types. And `net/lotus` with the impl of that interface for the Lotus API. Whenever we support a new client say `go-filecoin`, we can create `net/gofilecoin` as another impl of `net`.

**Comment by asutula** [comment]
nice, I like it. thanks!

**Comment by asutula** [comment]
Hey @jsign one more question for you. Currently, the only data I imagine augmenting the list of peers with is peer location. Do you think we should create a proper index with persistence and all or just keep the list in memory, rebuilding it every time the server starts up and/or when there is an update trigger event (like chain update)?

**Comment by asutula** [comment]
The main reason I can think of to persist the data is to not have to run the location query logic all the time, but not sure how costly that is and if it's worth the added complexity.

**Comment by jsign** [comment]
I'd avoid caching until we have some data about that being a bottleneck or to long to run. The location resolving now is with a local database so shouldn't be a problem. And addrs of peerid may already be cached in lip2p host.

**Comment by asutula** [comment]
Ah ok. In that case, maybe I'll just add some location data model to the interface of our `Net` module's `Peers` method for now. The location data will just be included in the output whenever peers are queried.
