### ISSUE TITLE
Exploration: FFS Instance Multiple Addresses

### ISSUE THREAD

**Issue by asutula** [textileio/powergate#258]
Just typing out some thoughts and questions about how this might work...

Supporting multiple addresses is actually not looking too hard.

We can maintain a list of wallet addresses associated with the instance. Any operation that uses an address (`PushConfig`, `Replace`, etc) will need to verify that the address to be used exists in the list of instance addresses.

Methods that previously returned the instance wallet address or balance information will be converted to return a map or slice of address related information.

Main question I'm seeing is where and when to specify the address to use for a transaction. We can:

1. Add the wallet address as part of the `CidConfig` and `DefaultCidConfig` `Cold.FilConfig`. This provides a consistent way to specify the address, and gives us a place to store the default. Problem here is that it give less control or more difficult control over what address to use during a `Replace` operation since it will use the address that was previously used for that cid. Maybe that address is out of funds or no longer valid for some reason. This would require the user to realize that and push a new config for that cid before running `Replace`.
2. Require that an address is supplied with every call that needs one (`PushConfig`, `Replace`). We could still have a default if no address is specified. 

Another question is: Will it every be useful to know which address was used to store which cids? I don't think this information is already available since it was implied before to be the instance address. Do we want to add some tracking of wallet address <-> stored cid?

This also seems like an opportunity to add an optional display name associated with every address that is created. That looks like an easy change by modeling an address as a struct with `name` and `addr` fields, both will be persisted.

**Comment by jsign** [comment]
> Main question I'm seeing is where and when to specify the address to use for a transaction.

Regarding both options, I think we'll need a mixture. When a _CidConfig_ is renewed or repaired, it needs some address to indicate who will pay for that work. So sounds like the _CidConfig_ should have some _RenewRepairAddress_ or similar. Now it assumes it's the same address that pushed the _CidConfig_, but it might be a good opportunity to let the client select that.

Also, I agree that for _Replace_ sounds a bit odd or something is missing. 
I think we should add an optional _CidConfig_ option for _Replace_, identical to _PushConfig_. If nothing is passed, it will use the same _CidConfig_ as the replaced _Cid_ (what it does now). But if the caller wants to change the address or even other facts about the configuration (still replacing the old cid), then it can do it.

What do you think?

> Another question is: Will it every be useful to know which address was used to store which cids? I don't think this information is already available since it was implied before to be the instance address. Do we want to add some tracking of wallet address <-> stored cid?

I guess I'd say _yes_, if that's is necessary for some client. It sounds to me that we'll also need some other APIs to get all past jobs from a _Cid_, old _Cid Logs_ to show more details, etc. But I was waiting more to have a clear view of what would be needed. In short, yeah, most prob we'll discover some more query-style apis to do.

> This also seems like an opportunity to add an optional display name associated with every address that is created. That looks like an easy change by modeling an address as a struct with name and addr fields, both will be persisted.

Sounds good.

**Comment by asutula** [comment]
Ok cool, sounds like we're on the same page when it comes to specifying an address to use, think I can make some progress there.

Re: query cids by address, etc... Yea I was just assuming that might be useful, but you're right; Let's let the requirements drive those things. I'll dig more into the features list and see if that is even necessary.
