### ISSUE TITLE
ffs: create wallet address

### ISSUE THREAD

**Issue by asutula** [textileio/powergate#273]
choose type

- [x] BLS
- [x] Secp256k1

**Comment by asutula** [comment]
@jsign have any ideas what might be meant by multisig and how it might relate to pg?

**Comment by jsign** [comment]
> @jsign have any ideas what might be meant by multisig and how it might relate to pg?

Filecoin supports multisig addresses. 
These addresses are controlled by multiple actors, and things can be signed for these addresses with a minimum configurable threshold of K (K<=N) actors. Say, for sending funds from this account you need K from the N people that own the address.

Currently, multisig addresses aren't used in PG. How they can be related, I'm not that sure about. The only obvious thing that I might think about is adding support to create these kinds of wallets, but only for send-receive actions. Using them for deals might be possible, but I don't have that much clear.

**Comment by asutula** [comment]
Removing multisig here because it's really a separate thing that will take some time. Tracking here https://github.com/textileio/powergate/issues/361
