### ISSUE TITLE
ffs: cid activity log

### ISSUE THREAD

**Issue by asutula** [textileio/powergate#290]
When you click on a file or folder, you should be able to see Activity relating to the file

**Comment by asutula** [comment]
@jsign, are the logs for a cid persisted? If so, could we provide a way to query the log items from the past? This could be a typical request response thing or a channel with a buffer that gets filled immediately with item from the past in the current `WatchLogs`.

**Comment by jsign** [comment]
> @jsign, are the logs for a cid persisted? If so, could we provide a way to query the log items from the past? This could be a typical request response thing or a channel with a buffer that gets filled immediately with item from the past in the current `WatchLogs`.

Yes, they're persisted so past logs are recoverable.
Sure, we can make a new API for that.

**Comment by asutula** [comment]
This is now supported through the `ffs.watchLogs` api. You need to pass the `withHistory(true)` option and the listener will immediately receive all previous log events, and then will continue to receive any new log events
