### ISSUE TITLE
wallet: create multisig wallet address

### ISSUE THREAD

**Issue by asutula** [textileio/powergate#361]
looks like we'll need the test net to get further along before we can experiment with implementing this.

**Comment by Kenny-zhao** [comment]
当前市场主流的钱包产品是谁拥有助记词或私钥就可以直接将资金转走，这其实存在很大的安全隐患。

如果交易所内部出现内鬼，对方可以轻而易举将资金全部转走；或是多合伙人（老板）管理同一钱包资产，单签可能导致资产控制权偏向某个人，导致出现资产安全问题。

优盾钱包3.0的多签模式将权限分离，通过多签模式参与管理资产的合伙人，可自定义配置每个合伙人在多签管理中的权重比例，当参与多签的任何一个合伙人发送转账交易时，都需要部分或全部合伙人同意才能完成转账，保证资金的安全，也平衡了各管理者的权限。

**Comment by asutula** [comment]
Thanks, just putting the translation here for others:

> In the current mainstream wallet products in the market, whoever has a mnemonic or private key can directly transfer funds away, which actually poses a great security risk.
> 
> If there is an internal ghost in the exchange, the other party can easily transfer all the funds away; or multiple partners (bosses) manage the same wallet assets. Single signing may lead to asset control biased to one person, resulting in asset security problems.
> 
> Youdun Wallet 3.0's multi-signature mode separates permissions. Partners participating in asset management through the multi-signature mode can customize the weight ratio of each partner in multi-signature management. When any partner participating in multi-signature sends When transferring transactions, some or all partners need to agree to complete the transfer, ensuring the safety of funds and balancing the authority of each manager.
