### ISSUE TITLE
ffs: data size

### ISSUE THREAD

**Issue by asutula** [textileio/powergate#364]
I'm trying to see how we can report on the size and total size of data stored in ffs. The only `size` I see for data associated with a cid is `CidInfo.Hot.Size`. Seems like in the case of cold-only storage, we won't have any size information. Should we move `Size` up a level to `CidInfo` and always set it?

**Comment by asutula** [comment]
Looks like the size calculation actually comes from storing the data in hot storage. Looking to see if there is something similar for cold

**Comment by asutula** [comment]
Appears that filecoin data size can be queried _after_ a storage deal is made by calling Lotus' `ClientGetDealInfo`. We're not really exposing this method, but we can potentially, or at least call it internally to get the size information to set on some struct.

**Comment by asutula** [comment]
Hmm, this is a bit complicated and I don't have enough information to figure out the answer. `Size` can be reported by Lotus' `GetDealInfo`, but that might be for a single "piece". If a stored cid is split across multiple pieces, you'd have to sum them to get a total size. Additionally, PG supports storing data in multiple miners, each with a separate deal, thus separate (but hopefully equal) answers for `Size` of each piece deal. I'm only about 85% confident of that analysis, though ;)

**Comment by asutula** [comment]
Ok, because of some recent updates to Lotus and Powergate (https://github.com/textileio/powergate/pull/414/files), size is now available on both hot and cold storge info. 

Just some context, @jsign, should we expect the size reported in hot and cold info to be the same or different? If they're different, why? (that is fine, just want to be sure we understand why/how to use the data)

**Comment by jsign** [comment]
> Ok, because of some recent updates to Lotus and Powergate (https://github.com/textileio/powergate/pull/414/files), size is now available on both hot and cold storge info.
> 
> Just some context, @jsign, should we expect the size reported in hot and cold info to be the same or different? If they're different, why? (that is fine, just want to be sure we understand why/how to use the data)

I think we should expect both to be the same now. It should be the cumulative size of the DAG.

**Comment by asutula** [comment]
Ok thanks, that's easy.
