### ISSUE TITLE
Devnet "make build" instructions in readme don't seem to work

### ISSUE THREAD

**Issue by kathekon** [textileio/powergate#475]
Forgive me as I'm new to docker but in your Devnet instructions in the readme, "make build" results in:

make: *** No rule to make target 'build'.  Stop.

I should note that the previous instruction, "make devnet," worked fine.

**Comment by jsign** [comment]
`make build` should be run in the main repo folder. `make devnet` in the `docker` folder.
Maybe that's your scenario?

**Comment by kathekon** [comment]
Thanks.  That got me closer, but that failed too.  This is likely user-error on my part...  Thanks again!

curt@ubuntu:~/powergate$ make build
CGO_ENABLED=0 go install ./...
go: finding github.com/ipfs/go-ipfs-files v0.0.2
go: finding github.com/libp2p/go-libp2p-autonat v0.2.3
go: finding github.com/ipfs/go-ipfs-posinfo v0.0.1
go: finding github.com/warpfork/go-wish v0.0.0-20200122115046-b9ea61034e4a
go: finding github.com/prometheus/procfs v0.1.0
go: finding github.com/libp2p/go-yamux v1.3.6
go: finding golang.org/x/tools v0.0.0-20200318150045-ba25ddc85566
go: finding golang.org/x/crypto v0.0.0-20200427165652-729f1e841bcc
go: finding golang.org/x/crypto v0.0.0-20190618222545-ea8f1a30c443
go: finding golang.org/x/net v0.0.0-20200519113804-d87ec0cfa476
go: finding golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3
go: finding github.com/libp2p/go-libp2p v0.9.2
go: finding github.com/filecoin-project/go-bitfield v0.0.0-20200416002808-b3ee67ec9060
go: finding github.com/btcsuite/btcd v0.0.0-20190523000118-16327141da8c
go: finding github.com/ipfs/go-bitswap v0.1.0
go: finding github.com/whyrusleeping/go-logging v0.0.0-20170515211332-0457bb6b88fc
go: finding golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
go: finding github.com/btcsuite/btcutil v0.0.0-20190425235716-9e5f4b9a998d
go: finding google.golang.org/genproto v0.0.0-20200608115520-7c474a2e3482
go: finding github.com/ipfs/go-hamt-ipld v0.1.1-0.20200501020327-d53d20a7063e
go: finding github.com/whyrusleeping/cbor-gen v0.0.0-20200501014322-5f9941ef88e0
go: finding golang.org/x/crypto v0.0.0-20170930174604-9419663f5a44
go: finding github.com/btcsuite/snappy-go v0.0.0-20151229074030-0bdef8d06723
go: finding github.com/jbenet/go-temp-err-catcher v0.1.0
go: finding golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: finding github.com/jessevdk/go-flags v0.0.0-20141203071132-1679536dcc89
go: finding github.com/libp2p/go-libp2p-peerstore v0.1.4
go: finding github.com/btcsuite/goleveldb v0.0.0-20160330041536-7834afc9e8cd
go: finding golang.org/x/mod v0.2.0
go: finding google.golang.org/appengine v1.1.0
go: finding github.com/uber/jaeger-lib v2.2.0+incompatible
go: launchpad.net/gocheck@v0.0.0-20140225173054-000000000087: bzr branch --use-existing-dir https://launchpad.net/~niemeyer/gocheck/trunk . in /home/curt/go/pkg/mod/cache/vcs/f46ce2ae80d31f9b0a29099baa203e3b6d269dace4e5357a2cf74bd109e13339: exec: "bzr": executable file not found in $PATH
go: finding github.com/btcsuite/btcd v0.0.0-20190213025234-306aecffea32
go: finding github.com/envoyproxy/go-control-plane v0.9.0
go: finding golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e
go: finding github.com/prometheus/procfs v0.0.0-20190507164030-5867b95ac084
go: finding github.com/lucas-clemente/quic-go v0.15.7
go: finding github.com/prometheus/common v0.4.0
go: finding github.com/libp2p/go-ws-transport v0.3.1
go: finding github.com/jonboulle/clockwork v0.1.1-0.20190114141812-62fb9bc030d1
go: finding golang.org/x/net v0.0.0-20200226121028-0de0cce0169b
go: finding golang.org/x/tools v0.0.0-20191030062658-86caa796c7ab
go: finding github.com/ipfs/go-datastore v0.0.1
go: finding golang.org/x/lint v0.0.0-20190313153728-d0100b6bd8b3
go: finding github.com/ipfs/go-log/v2 v2.0.5
go: finding golang.org/x/net v0.0.0-20200602114024-627f9648deb9
go: finding github.com/kabukky/httpscerts v0.0.0-20150320125433-617593d7dcb3
go: finding github.com/gogo/status v1.1.0
go: finding github.com/ipfs/go-ipfs-blockstore v0.1.0
go: finding github.com/btcsuite/websocket v0.0.0-20150119174127-31079b680792
go: finding github.com/beorn7/perks v1.0.0
go: finding golang.org/x/mod v0.0.0-20190513183733-4bf6d317e70e
go: finding github.com/libp2p/go-libp2p-record v0.1.0
go: finding github.com/golang/protobuf v1.4.1
go: finding github.com/gogo/googleapis v1.4.0
go: finding golang.org/x/tools v0.0.0-20190524140312-2c0ae7006135
go: finding github.com/weaveworks/common v0.0.0-20200512154658-384f10054ec5
go: finding github.com/davecgh/go-spew v0.0.0-20171005155431-ecdeabc65495
go: finding github.com/gorilla/handlers v1.4.2
go: finding github.com/drand/kyber-bls12381 v0.1.0
go: finding golang.org/x/crypto v0.0.0-20190225124518-7f87c0fbb88b
go: finding github.com/google/go-cmp v0.3.1
go: finding github.com/dgraph-io/badger v1.6.1
go: finding honnef.co/go/tools v0.0.0-20190523083050-ea95bdfd59fc
go: finding github.com/ipfs/go-datastore v0.3.1
go: finding github.com/rogpeppe/go-internal v1.3.0
go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: finding golang.org/x/crypto v0.0.0-20190211182817-74369b46fc67
go: finding github.com/sercand/kuberesolver v2.4.0+incompatible
go: finding github.com/davidlazar/go-crypto v0.0.0-20190912175916-7055855a373f
go: finding golang.org/x/tools v0.0.0-20191130070609-6e064ea0cf2d
go: finding github.com/spacemonkeygo/openssl v0.0.0-20181017203307-c2dcc5cca94a
go: finding github.com/libp2p/go-libp2p v0.8.3
go: finding github.com/ipfs/go-ipfs-ds-help v0.0.1
go: finding github.com/google/renameio v0.1.0
go: finding github.com/aead/siphash v1.0.1
go: finding golang.org/x/net v0.0.0-20190227160552-c95aed5357e7
go: finding github.com/libp2p/go-yamux v1.3.5
go: finding github.com/mattn/go-isatty v0.0.3
go: finding github.com/ipfs/go-datastore v0.3.0
go: finding gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
go: finding github.com/davidlazar/go-crypto v0.0.0-20170701192655-dcfb0a7ac018
go: finding github.com/mr-tron/base58 v1.1.1
go: finding github.com/libp2p/go-libp2p-pubsub v0.3.2-0.20200527132641-c0712c6e92cf
go: finding github.com/btcsuite/go-socks v0.0.0-20170105172521-4720035b7bfd
go: finding github.com/ipfs/go-log/v2 v2.0.2
go: finding github.com/libp2p/go-libp2p-core v0.5.5
go: finding github.com/opentracing-contrib/go-grpc v0.0.0-20191001143057-db30781987df
go: finding golang.org/x/net v0.0.0-20180826012351-8a410e7b638d
go: finding github.com/libp2p/go-libp2p-core v0.0.2
go: finding github.com/btcsuite/btclog v0.0.0-20170628155309-84c8d2346e9f
go: finding github.com/prometheus/common v0.10.0
go: finding golang.org/x/sys v0.0.0-20200519105757-fe76b779f299
go: finding github.com/gorilla/rpc v1.2.0
go: finding github.com/client9/misspell v0.3.4
go: finding golang.org/x/tools v0.0.0-20200130002326-2f3ba24bd6e7
go: finding github.com/gin-gonic/gin v1.4.0
go: finding github.com/prometheus/client_golang v1.6.0
go: finding github.com/minio/sha256-simd v0.1.0
go: finding cloud.google.com/go v0.26.0
go: finding golang.org/x/sys v0.0.0-20200427175716-29b57079015a
go: finding github.com/uber/jaeger-client-go v2.23.1+incompatible
go: finding github.com/ipfs/go-path v0.0.3
go: finding go.etcd.io/bbolt v1.3.4
go: finding github.com/mattn/go-colorable v0.1.1
go: finding github.com/opentracing-contrib/go-stdlib v1.0.0
go: finding github.com/libp2p/go-libp2p-crypto v0.1.0
go: finding github.com/yuin/goldmark v1.1.25
go: finding github.com/ipfs/go-merkledag v0.0.3
go: finding github.com/libp2p/go-sockaddr v0.1.0
go: finding github.com/kkdai/bstream v0.0.0-20161212061736-f391b8402d23
go: finding golang.org/x/sys v0.0.0-20200106162015-b016eb3dc98e
go: finding github.com/prometheus/tsdb v0.7.1
go: finding github.com/minio/sha256-simd v0.0.0-20190131020904-2d45a736cd16
go: finding github.com/multiformats/go-multihash v0.0.7
go: finding golang.org/x/crypto v0.0.0-20200604202706-70a84ac30bf9
go: finding github.com/btcsuite/winsvc v1.0.0
go: finding github.com/ipfs/go-merkledag v0.0.6
go: finding github.com/jrick/logrotate v1.0.0
go: finding golang.org/x/sys v0.0.0-20180202135801-37707fdb30a5
go: finding github.com/ipfs/go-unixfs v0.0.4
go: finding github.com/sirupsen/logrus v1.6.0
go: finding github.com/kr/pretty v0.2.0
go: finding github.com/grpc-ecosystem/grpc-gateway v1.14.6
go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
go: finding github.com/opentracing/opentracing-go v1.0.2
go: finding github.com/dave/jennifer v1.4.0
go: finding github.com/ipfs/go-ipld-cbor v0.0.1
go: finding github.com/nikkolasg/hexjson v0.0.0-20181101101858-78e39397e00c
go: finding google.golang.org/grpc v1.27.0
go: finding github.com/ipfs/go-log v1.0.1
**go: error loading module requirements
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1**

**Comment by jsign** [comment]
Seems something is failing in your Go tooling. 

What version of Go do you have installed? (`go version`).
We're targeting 1.14. In my particular case:
```bash
$ go version
go version go1.14.4 darwin/amd64
```
And not having compile issues.

**Comment by kathekon** [comment]
That was it!  I was on 1.12 (in Ubuntu)
