### ISSUE TITLE
pow/cli: consider adding folders helper

### ISSUE THREAD

**Issue by jsign** [textileio/powergate#504]
Consider supporting `pow ffs addToHot` to folders.

**Comment by rajdeepbharati** [comment]
Could someone give pointers on how to go about adding folder helper in the go client api?

**Comment by jsign** [comment]
@rajdeepbharati , you can `ipfs add -r` to the IPFS node directly. We're planning to add a `pow ffs` sub-cmd helper soon.

**Comment by rajdeepbharati** [comment]
@jsign Thanks, I will use that for now :)
