### ISSUE TITLE
ffs: Unable to store string to Lotus testnet using PowerGate FFS

### ISSUE THREAD

**Issue by ltfschoen** [textileio/powergate#521]
Please see the description in this PR https://github.com/ltfschoen/ethquad/pull/7, which includes screenshots, and a list of issues I've encountered, and the list of steps you could follow to replicate the issues.

**Comment by asutula** [comment]
Hi @ltfschoen. You issue PR mentions "local testnet". I assume that is our localnet docker compose setup? Please see the localnet docs towards the top where it talks about BIGSECTORS and acceptable file sizes to store in Powergate cold storage.

https://docs.textile.io/powergate/localnet/

> Not using --bigsectors will limit you to storing files of around 700 bytes and deals will complete in 30-60 seconds. Using --bigsectors will allow you to store files anywhere from 1Mb to 400Mb, but deals will complete in 3-4 minutes. Be sure to choose the value that makes sense for your development scenario.

So whether or not you use big sectors, a cid string is too small. There is also be minimum file size requirements in Filecoin test net and main net.

**Comment by asutula** [comment]
Pretty sure that is causing your problem. Feel free to open this back up if not.

**Comment by ltfschoen** [comment]
Thanks I'll try that out. Yes, I'm trying to get it to work on the localnet first https://github.com/textileio/powergate/blob/master/docker/docker-compose-localnet.yaml
