### ISSUE TITLE
Does the powergate-docker support arm?

### ISSUE THREAD

**Issue by Jason-Wanxt** [textileio/powergate#584]
I downloaded powergate-docker, but after i run the make localnet,it occured "exec format error".If powergate-docker support arm support arm, where can i download it?

**Comment by jsign** [comment]
I've never compiled Powergate on ARM. I wouldn't expect that to be a problem, but yes, all Docker images we make are for x86_64/linux.

If you have an ARM machine, you could run: `docker build -t powergate:arm .` in the root of the powergate repo.

**Comment by Jason-Wanxt** [comment]
> I've never compiled Powergate on ARM. I wouldn't expect that to be a problem, but yes, all Docker images we make are for x86_64/linux.
> 
> If you have an ARM machine, you could run: `docker build -t powergate:arm .` in the root of the powergate repo.

Thanks,i have complete images of powergate and go-ipfs, but i didn't find textile/lotus-devnet image or dockerfile,where can i find it?

**Comment by jsign** [comment]
Sure. The code of `textile/lotus-devnet` is [here](https://github.com/textileio/lotus-devnet).
That build requires Rust, OpenCL so it's a bit hairier. I'm not even sure the Lotus dependencies might be compilable in ARM, but you'll soon discover. :)
