### ISSUE TITLE
funding new master addr: unknown faucet for network testnetnet

### ISSUE THREAD

**Issue by askender** [textileio/powergate#601]
FATAL	powd	powd/main.go:71	starting server: creating wallet module: funding new master addr: unknown faucet for network testnetnet

**Comment by jsign** [comment]
You can't use `--autocreatemasteraddr` in Testnet since there's no public un-authorized faucet.
Unfortunately, you'll have to create a wallet address in the Lotus node, fund it (using the GH authorized faucet, asking someone (I can help), etc) and then using the flag `--lotusmasteraddr`.

**Comment by askender** [comment]
Thanks!   I am using `--lotusmasteraddr` now.     I am already in space race 1 & 2, my github account is all used, I will try fund myself.         `asking someone` will bother others.    my address: t3ulpilos7whd2aj6gchyb7nhlxzwjnrjlsl2k7bieyove6zh472vgyyr3yozrlvkxnw4rs2nbchsabml3ygrq

I am in slingshot too, I think it will be interesting.   powergate is nice. the pow commandline is much cooler than lotus . I am learning it. 

By the way,  where can I finding more docs or tutorials?

More Info you maybe not interested:
- I have finish the python code to interact with lotus using commandline to store (and retrieve)   (ipfs related code is seperate, and not written yet).   It is easy, bare-metal, but really ugly.
- I am not too familiar with grpc in python.    one option for me: <https://github.com/pygate/pygate-gRPC> do you know the project?  what's your suggestion?   use nodejs?
- so I think if I am building a really simple app, I will not need full-featured grpc. just commandline is ok.  if the commandline can output pure json, it will be much better.  

I am also in hackfs and appllo, and using slack. Where is the best place to talk about the powergate? In github issue?
I maybe can help write some docs and tutorials for beginners in future.

**Comment by jsign** [comment]
You might be interested in the [docs](https://docs.textile.io/powergate/ffs/).

The best place to have random chat about Powergate `#powergate-users` in the Filecoin slack channel. You can find the `pygate` guys around there so maybe that's a better place to ask questions about that.

**Comment by askender** [comment]
Thanks.  close the issue.
