### ISSUE TITLE
Verify address for PushConfig

### ISSUE THREAD

**Issue by asutula** [textileio/powergate#615]
In the FFS API, PushConfig should verify that the address to be used for storage is actually owned by the FFS instance.

**Comment by jsign** [comment]
Aren't we already checking this [here](https://github.com/textileio/powergate/blob/7e02838f2a59c47de23f7f53a92fcd4ed0901bec/ffs/api/api_actions.go#L37)?

See also [this](https://filecoinproject.slack.com/archives/C01ARR6BD2M/p1601042411043300?thread_ts=1601042087.043000&cid=C01ARR6BD2M) convo.

Or maybe I'm misunderstanding the issue, if that's the case dismiss.

**Comment by asutula** [comment]
Yep, didn't see that.
