### ISSUE TITLE
Include `pow ffs sign <challenge>` and `pow ffs verify <msg> <addr>` methods

### ISSUE THREAD

**Issue by andrewxhill** [textileio/powergate#618]
Pow users are going to need the ability to sign arbitrary messages with their wallet identities. This will be a necessary step for getting rewarded in SR2. 

1. `pow ffs sign` would be great
2. `pow ffs verify` would complete the feature, though isn't required by SR2

**Comment by pooja** [comment]
Thanks! For context, the verification flow we're running on the lotus side is:


We run: `echo "Slingshot Is Officially Open" \| xxd -p536c696e6773686f74204973204f6666696369616c6c79204f70656e0a`

They do: `lotus wallet sign  {{TheirAddressHere}}  {{The Hex From Above}}`

We run: `lotus wallet verify  {{TheirAddress}}  $( echo "Slingshot Is Officially Open" \| xxd -p )  {{TheSignatureTheySubmitted}}`

Would be great if we could expose some of the same functionality (as Andrew mentions, esp the sign method) through pow
