### ISSUE TITLE
Investigate relationship between CIDs listed in FFS.Info and FFS.Show(All)

### ISSUE THREAD

**Issue by asutula** [textileio/powergate#629]
Seems that cids listed in `Info` are sometimes not found using `Show` and `ShowAll`. Want to understand why this is and what the best UX should be.

**Comment by ukstv** [comment]
Please, report the current status of the job in Show instead of saying CID is not found.

**Comment by asutula** [comment]
This is fixed in Powergate v1.0.0. Got rid of some confusing API methods like `show` and `info`. You can now ask for cid info and get back a summary of the current storage state, any jobs, etc.

**Comment by ukstv** [comment]
Supercool. Thanks!
