### ISSUE TITLE
ffs: multi tenancy

### ISSUE THREAD

**Issue by jsign** [textileio/powergate#632]
Since the underlying `go-ipfs` node doesn't have multitenant capabilities, pinset managing relies on the assumption that one FFS instance owns a pined Cid. 

This is a bit problematic when different FFS instances are used ina multi-tenant way. As a solution, we could think of doing some reference counting on the pinset, so different instances can pin (and re pin) Cids, and also unpin them. This would mean that only when all FFS instances have unpined the same Cid, the real unpinning in `go-ipfs` should happen.

We should also think about shifting the _CidLogger_ to not log messages keyed by _Cid_, since that would mean interfering logs between different FFS instances. The key should be (FFSInstanceId, Cid).

**Comment by asutula** [comment]
Safe to close this?

**Comment by jsign** [comment]
Yes!
