### ISSUE TITLE
after upgrade to lotus 0.8.1, powd got ` invalid memory address or nil pointer dereference` and cann't start

### ISSUE THREAD

**Issue by askender** [textileio/powergate#634]
```
2020-10-01T12:51:08.908+0800	INFO	index-miner	module/onchain.go:67	current state height 105184, new tipset height 107377
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x12171bd]

goroutine 1507 [running]:
github.com/textileio/powergate/index/ask/runner.getMinerStorageAsk(0x1cb3160, 0xc0008ce200, 0xc0003f7b80, 0xc000665ca8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/xx/powergate/index/ask/runner/runner.go:285 +0x6dd
github.com/textileio/powergate/index/ask/runner.generateIndex.func1(0xc000ca7560, 0xc00081ec50, 0xc0003f7b80, 0xc0006c8248, 0xc0006a4060, 0xc000665ca8, 0x4)
	/home/xx/powergate/index/ask/runner/runner.go:216 +0xa7
created by github.com/textileio/powergate/index/ask/runner.generateIndex
	/home/xx/powergate/index/ask/runner/runner.go:214 +0x24e
```

besides, lotus daemon is already synced.

**Comment by nad010286** [comment]
same issue, please lets me know if you managed to fixed this

**Comment by jsign** [comment]
We haven' tested v0.8.1 yet, most probably that means there's a breaking API.
v0.8.1 is an optional update, so hold a bit until I can take a look which will be soon.

**Comment by kalambet** [comment]
Same issue here.
This is happening bc `sask` object returned here:
https://github.com/textileio/powergate/blob/d83c403b88a06e2380d05ad8bde6e88fcf376200/index/ask/runner/runner.go#L280

Has all `nil` members.
Obvious and dumb patch would be just to add ` || sask.Ask == nil` here:
https://github.com/textileio/powergate/blob/d83c403b88a06e2380d05ad8bde6e88fcf376200/index/ask/runner/runner.go#L281
(running it for couple of hours seems fine)

But from the sanity perspective this is not a fix but rather a context-unaware patch. Maybe it's worth to investigate why such situation happening. From return values perpective it's either `err != nil` or valid (initialized but empty, for example) return object.

**Comment by jsign** [comment]
Yes, since Lotus is still v0, every patch release could change the APIs. 

I'll create a branch today and a docker image with a quick update of the client and some fix for this so eager people can update their Powergates. To merge it in master I still have to do some other stuff to localnet for the CI etc.

More info soon here.

**Comment by jsign** [comment]
If you want to give an eager try to [this](https://github.com/textileio/powergate/pull/644) PR branch, should be good.

**Comment by jsign** [comment]
Docker image preview if using docker `textile/powergate:v0.7.0-rc1`
