### ISSUE TITLE
ffs: make ipfs repo gc safe

### ISSUE THREAD

**Issue by jsign** [textileio/powergate#663]
Currently, there isn't a 100% safe way to run `ipfs repo gc` in the underlying `go-ipfs` node. Ideally, it would be good to make running `ipfs repo gc` safe in any instant so can be easily scheduled on some cron job or similar without coordination with Powergate. This problem is tricky for multiple reasons.

*Case 1*:
Consider the case that a user does `pow ffs stage`. A priori that Cid data _would_ be used in a further `pow ffs config push`, but there's no guarantee of that. So a priori looks like a good idea to keep our policy of not pinning automatically everything on `pow ffs stage`. But if a `go-ipfs` GC is run between `pow ffs stage` and `pow fffs config push`, then the data could be missing when the Job is executed.

If we always pin on `pow ffs stage`, then we should provide some way to manually free all pinned staged data, since the user could simply call `pow ffs stage` for multiple Cids, but end up only pushing a configuration for a single one. So, what about the other 2 pinned ones? Can't be pinned forever.

*Case 2*:
If a StorageConfig is pushed with `Hot.Enabled: true`, then while the Job is executing there's no risk that a go-ipfs GC can delete the data to make deals.

If a StorageConfig is pushed with `Hot.Enabled: false`, then we have a border case situation. Whenever that Cid data is available in the `go-ipfs` node (being `pow ffs stage`d before, or fetched from the IPFS network), there's the risk that it gets GCed before the data is transferred to miners.

The above seems to indicate that the value of `Hot.Enabled: xxx` shouldn't be important, and we should always pin the Cid data whenever is available in the `go-ipfs` node. Only *after* the deal data was transferred to all miners, we can:
- Keep the data pinned if `Hot.Enabled: true`.
- Unpin the data if `Hot.Enabled: true`.

This way, we keep the data safe from being GCed in the wrong moment.

I'm still not completely sure about the right solution, so this is mostly a brain dump.
Of course, the worst case scenario of this is the Job failing and the user having to retry or re-stage the data... so isn't a fatal situation.

**Comment by asutula** [comment]
That all makes sense. I think for Case 1 it would be reasonable to pin the data on `stage` and set a timer after which the data will be unpinned if `config push` isn't called.

**Comment by asutula** [comment]
Safe to close this?

**Comment by jsign** [comment]
Yes.
