### ISSUE TITLE
Can't use on WSL when connecting to local lotus node and local ipfs daemon "context deadline exceeded"

### ISSUE THREAD

**Issue by ChristianOConnor** [textileio/powergate#849]
I am using WSL Ubuntu 20.04 on Windows 10. I can't get powergate to work by connecting it to my already installed lotus node and already installed ipfs-go.  
  
I installed lotus, ipfs-go, pow, and powd. I waited for the lotus daemon to finish syncing then I launched ipfs with `ipfs daemon`, then the pow daemon in a screen session with `powd --lotustoken <mylotustokenhere>`.

So the lotus daemon is synced and running, the ipfs daemon is running, and the powergate daemon is also running connected to the lotus daemon through the admin auth token. I already staged a directory and got a cid (through powergate) with the command `pow data stage path/to/dir` and got a 'bafy' starting IPFS hash. The directory is about 5GB in size. I created a random data bin file through a dd command. I chose to make it 5GB because I noticed that a lot of miners want you to make the job for more than 4GB. I ran the command `pow config apply --watch <CID> -o -c custom-072321-config.json`. This was my custom-072321-config.json file.  
  
```
{
  "hot":  {
    "enabled":  false,
    "allowUnfreeze":  false,
    "unfreezeMaxPrice":  "0",
    "ipfs":  {
      "addTimeout":  "900"
    }
  },
  "cold":  {
    "enabled":  true,
    "filecoin":  {
      "replicationFactor":  "1",
      "dealMinDuration":  "518400",
      "excludedMiners":  [],
      "trustedMiners":  [],
      "countryCodes":  [],
      "renew":  {
        "enabled":  false,
        "threshold":  "0"
      },
      "address":  "<my filecoin address with 400000000 attoFIL>",
      "maxPrice":  "100000000000",
      "fastRetrieval":  true,
      "dealStartOffset":  "8640",
      "verifiedDeal":  false
    }
  },
  "repairable":  false
}
```  
  
But the job failed... IDK why?

This was my error that I got:  
  
```
                 JOB ID                |             STATUS             | MINER | PRICE | DEAL STATUS
---------------------------------------+--------------------------------+-------+-------+--------------
            <my job id here>           | JOB_STATUS_FAILED executing    |       |       |
                                       | cold-storage config: getting   |       |       |
                                       | cid cummulative size:          |       |       |
                                       | getting cid cummulative        |       |       |
                                       | size: calculating data size:   |       |       |
                                       | merkledag: not found           |       |       |
<myusername>@<mycompname>:~$
```  
  
So I removed all of the files from the IPFS daemon pinning system with `ipfs pin ls --type recursive | cut -d' ' -f1 | xargs -n1 ipfs pin rm` then ran `ipfs repo gc` to make sure that they were garbage collected. I ran `ipfs add -r --pin=false path/to/dir` and got a Q starting CID and ran the command `pow config apply --watch <CID> -o -c custom-072321-config.json` again with the new CID starting with a Q and I got the same error as above. So I figured that the original bafy starting CID and the Q starting CID were still describing the same directory. So I ran the original `pow config apply --watch <CID> -o -c custom-072321-config.json` command with the original `bafy` starting CID and after sticking on JOB_STATUS_EXECUTING for a long time, I got this error:  
  
```
                 JOB ID                |                                                              STATUS                                                              | MINER | PRICE | DEAL STATUS
---------------------------------------+----------------------------------------------------------------------------------------------------------------------------------+-------+-------+--------------
            <my job id here>           | JOB_STATUS_FAILED automatically staging cid: adding data to ipfs: Post                                                           |       |       |    
                                       | "http://127.0.0.1:5001/api/v0/pin/add?arg=%2Fipfs%2F<bafystaringCID>&recursive=true":                                            |       |       |    
                                       | context deadline exceeded                                                                                                        |       |       |    
```  
  
What am I doing wrong? How do I store my file on Filecoin?

**Comment by jsign** [comment]
> cold-storage config: getting cid cummulative size: getting cid cummulative size: calculating data size: merkledag: not found 

The reason for that error is a misconfiguration of the Lotus node, refer [here](https://docs.textile.io/powergate/faq/#i-see-a-log-error-computing-commp-failed-generating-commp-blockstore-block-not-found-what-does-this-mean) to see exactly what you need to do. Your error msg is different from the one mentioned in the FAQ, but is the same situation.

That configures Lotus to use the `go-ipfs` node to look for the data for making deals.

**Comment by ChristianOConnor** [comment]
> > cold-storage config: getting cid cummulative size: getting cid cummulative size: calculating data size: merkledag: not found
> 
> The reason for that error is a misconfiguration of the Lotus node, refer [here](https://docs.textile.io/powergate/faq/#i-see-a-log-error-computing-commp-failed-generating-commp-blockstore-block-not-found-what-does-this-mean) to see exactly what you need to do. Your error msg is different from the one mentioned in the FAQ, but is the same situation.
> 
> That configures Lotus to use the `go-ipfs` node to look for the data for making deals.

Oh awesome thanks you
