### ISSUE TITLE
Is There A Simple Way to Migrate Your Docker Powergate Install to A New Computer?

### ISSUE THREAD

**Issue by ChristianOConnor** [textileio/powergate#855]
I have been trying to migrate my install by doing the following commands:  
```
docker ps
```
Then get the id that corresponds with the lotus vm.  
  
```
docker cp <lotus container Id>:data/.lotus/config.toml docker_powergate_files_backups/072821/data_dot_lotus/
docker cp <lotus container Id>:data/.lotus/api docker_powergate_files_backups/072821/data_dot_lotus/
docker cp <lotus container Id>:data/.lotus/data-transfer docker_powergate_files_backups/072821/data_dot_lotus/
docker cp <lotus container Id>:data/.lotus/heapprof docker_powergate_files_backups/072821/data_dot_lotus/
docker cp <lotus container Id>:data/.lotus/journal docker_powergate_files_backups/072821/data_dot_lotus/
docker cp <lotus container Id>:data/.lotus/keystore docker_powergate_files_backups/072821/data_dot_lotus/
docker cp <lotus container Id>:data/.lotus/kvlog docker_powergate_files_backups/072821/data_dot_lotus/
docker cp <lotus container Id>:data/.lotus/repo.lock docker_powergate_files_backups/072821/data_dot_lotus/
docker cp <lotus container Id>:data/.lotus/token docker_powergate_files_backups/072821/data_dot_lotus/
docker cp <lotus container Id>:data/.lotus/datastore/client docker_powergate_files_backups/072821/data_dot_lotus/datastore/
docker cp <lotus container Id>:data/.lotus/datastore/metadata docker_powergate_files_backups/072821/data_dot_lotus/datastore/
docker cp <lotus container Id>:data/.lotus/datastore/staging docker_powergate_files_backups/072821/data_dot_lotus/datastore/

docker cp <ipfs container Id>:data/ipfs docker_powergate_files_backups/072821/data_ipfs/

docker cp <powergate container Id>:../root/.powergate docker_powergate_files_backups/072821/root_dot_powergate/
```  
  
This created a directory `072821` that I believe contains all of the relevant info for migrating the install from one computer to another.  
  
The only thing I don't know how to do is copy these files from the new host computer to the new docker machines. For example how would I execute the inverse of this command `docker cp <lotus container Id>:data/.lotus/config.toml docker_powergate_files_backups/072821/data_dot_lotus/` where I'm trying to copy the data INTO my docker machine instead of out of it.

**Comment by ChristianOConnor** [comment]
Also is there a simpler way to migrate my install from one computer to another?

**Comment by jsign** [comment]
To copy things to a container, you can do `docker hello.txt <container-name>:somwhere/path.txt` and similar.
Also, you could think of exporting the volumes attached to the containers for a more _clean_ copy.

**Comment by ChristianOConnor** [comment]
> To copy things to a container, you can do `docker hello.txt <container-name>:somwhere/path.txt` and similar.
> Also, you could think of exporting the volumes attached to the containers for a more _clean_ copy.

Okay cool, makes sense.
